### ISSUE TITLE
"aspect_dict" value can't use  "to" function

### ISSUE THREAD

**Issue by WEN6Lev57q4** [sunxiaojie99/MURAL#1]
Excuse me for following problem,
The reason of problem is that "aspect_dict" value can't use  "to" function in pretrain process. But how to solve it. Thanks a lot.
`Traceback (most recent call last):
  File "/project/miniconda3/envs/glm/lib/python3.10/site-packages/accelerate/utils/operations.py", line 155, in send_to_device
    return tensor.to(device, non_blocking=non_blocking)
TypeError: BatchEncoding.to() got an unexpected keyword argument 'non_blocking'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/miniconda3/envs/glm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/project/miniconda3/envs/glm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/project/Project/MURAL-main/src/tevatron/driver/pretrain.py", line 487, in <module>
    main()
  File "/project/Project/MURAL-main/src/tevatron/driver/pretrain.py", line 445, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/project/miniconda3/envs/glm/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/project/miniconda3/envs/glm/lib/python3.10/site-packages/transformers/trainer.py", line 1836, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/project/miniconda3/envs/glm/lib/python3.10/site-packages/accelerate/data_loader.py", line 461, in __iter__
    current_batch = send_to_device(current_batch, self.device)
  File "/project/miniconda3/envs/glm/lib/python3.10/site-packages/accelerate/utils/operations.py", line 157, in send_to_device
    return tensor.to(device)
  File "/project/miniconda3/envs/glm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 790, in to
    self.data = {k: v.to(device=device) for k, v in self.data.items()}
  File "/project/miniconda3/envs/glm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 790, in <dictcomp>
    self.data = {k: v.to(device=device) for k, v in self.data.items()}
AttributeError: 'dict' object has no attribute 'to'`

**Comment by WEN6Lev57q4** [comment]
transformers version is 4.30.0

**Comment by WEN6Lev57q4** [comment]
transformers version is 4.30.0
